[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m RADHA_MUSIC"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[envs]
PYTHON_VERSION = "3.10.0" 